### ISSUE TITLE
关于原书7.2.3霍夫线性变换的原理 p269页勘误一处

### ISSUE THREAD

**Issue by abc1044** [QianMo/OpenCV3-Programming-Book-Src#13]
绘制图7.18的参数有一处错误：
原文p269：点x1=9，**y1=4**和点x2=12，y2=3绘图，得到图7.18.

应该为：x1=9，**y1=5**

原文参数绘图：
![image](https://user-images.githubusercontent.com/18114052/96359897-64b88b00-114a-11eb-9b20-bd18337e9559.png)

更正后参数绘图：
![image](https://user-images.githubusercontent.com/18114052/96359905-74d06a80-114a-11eb-9d02-523d276d6a6f.png)

**Comment by QianMo** [comment]
你的勘误已收到，感谢
