### ISSUE TITLE
OpenCV3示例代码的第16个程序：imageROI= image(Rect(800,350,logo.cols,logo.rows));出错

### ISSUE THREAD

**Issue by ghost** [QianMo/OpenCV3-Programming-Book-Src#8]
OpenCV3.4下：
OpenCV3-examples的第16个示例程序第31行Mat image= imread("dota.jpg",199);
会导致44行imageROI构造出错。

具体出错原因分析如下：
在文件/opencv-3.4/modules/imgcodecs/include/opencv2/imgcodecs.hpp
    的第64行起，找到如下定义：
    //! Imread flags
    enum ImreadModes {
       IMREAD_UNCHANGED            = -1, //!< If set, return the loaded image as is (with alpha channel, otherwise it gets cropped).
       IMREAD_GRAYSCALE            = 0,  //!< If set, always convert image to the single channel grayscale image (codec internal conversion).
       IMREAD_COLOR                = 1,  //!< If set, always convert image to the 3 channel BGR color image.
       IMREAD_ANYDEPTH             = 2,  //!< If set, return 16-bit/32-bit image when the input has the corresponding depth, otherwise convert it to 8-bit.
       IMREAD_ANYCOLOR             = 4,  //!< If set, the image is read in any possible color format.
       IMREAD_LOAD_GDAL            = 8,  //!< If set, use the gdal driver for loading the image.
       IMREAD_REDUCED_GRAYSCALE_2  = 16, //!< If set, always convert image to the single channel grayscale image and the image size reduced 1/2.
       IMREAD_REDUCED_COLOR_2      = 17, //!< If set, always convert image to the 3 channel BGR color image and the image size reduced 1/2.
       IMREAD_REDUCED_GRAYSCALE_4  = 32, //!< If set, always convert image to the single channel grayscale image and the image size reduced 1/4.
       IMREAD_REDUCED_COLOR_4      = 33, //!< If set, always convert image to the 3 channel BGR color image and the image size reduced 1/4.
       IMREAD_REDUCED_GRAYSCALE_8  = 64, //!< If set, always convert image to the single channel grayscale image and the image size reduced 1/8.
       IMREAD_REDUCED_COLOR_8      = 65, //!< If set, always convert image to the 3 channel BGR color image and the image size reduced 1/8.
       IMREAD_IGNORE_ORIENTATION   = 128 //!< If set, do not rotate the image according to EXIF's orientation flag.
    };

也就是说imread（）函数的flag值为199会使图片变小，导致44行imageROI构造出错。

**Comment by QianMo** [comment]
感谢反馈
